# .github/actions/send-email/action.yml
name: 'Send Email'
description: 'Send email via SMTP with retry support'
author: 'Platform Engineering'

inputs:
  smtp_server:
    description: 'SMTP server hostname'
    required: true
  smtp_port:
    description: 'SMTP server port'
    required: false
    default: '587'
  smtp_username:
    description: 'SMTP authentication username'
    required: false
  smtp_password:
    description: 'SMTP authentication password'
    required: false
  sender:
    description: 'Email sender address'
    required: true
  receivers:
    description: 'Email receivers (comma-separated)'
    required: true
  subject:
    description: 'Email subject'
    required: true
  body:
    description: 'Email body content (HTML supported)'
    required: false
  body_file:
    description: 'Path to file containing email body'
    required: false
  max_retries:
    description: 'Maximum retry attempts'
    required: false
    default: '3'
  retry_delay:
    description: 'Initial retry delay in seconds'
    required: false
    default: '1.0'
  timeout:
    description: 'SMTP connection timeout in seconds'
    required: false
    default: '10'

outputs:
  status:
    description: 'Email send status (success/failed)'
    value: ${{ steps.send.outputs.status }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Send email
      id: send
      shell: bash
      env:
        SMTP_SERVER: ${{ inputs.smtp_server }}
        SMTP_PORT: ${{ inputs.smtp_port }}
        SMTP_USERNAME: ${{ inputs.smtp_username }}
        SMTP_PASSWORD: ${{ inputs.smtp_password }}
        EMAIL_SENDER: ${{ inputs.sender }}
        EMAIL_RECEIVER: ${{ inputs.receivers }}
        SUBJECT: ${{ inputs.subject }}
        EMAIL_BODY: ${{ inputs.body }}
        BODY_FILE: ${{ inputs.body_file }}
        SMTP_MAX_RETRIES: ${{ inputs.max_retries }}
        SMTP_RETRY_DELAY: ${{ inputs.retry_delay }}
        SMTP_TIMEOUT: ${{ inputs.timeout }}
      run: |
        if python ${{ github.action_path }}/send_email.py; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=failed" >> $GITHUB_OUTPUT
          exit 1
        fi

# Example Workflow

# .github/workflows/example.yml
name: Example Workflow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: echo "Building..."

      - name: Send success notification
        if: success()
        uses: ./.github/actions/send-email
        with:
          smtp_server: ${{ secrets.SMTP_SERVER }}
          smtp_port: '587'
          smtp_username: ${{ secrets.SMTP_USERNAME }}
          smtp_password: ${{ secrets.SMTP_PASSWORD }}
          sender: 'ci@yourcompany.com'
          receivers: 'team@yourcompany.com,lead@yourcompany.com'
          subject: '✅ Build Success - ${{ github.repository }}'
          body: |
            <h2>Build Successful</h2>
            <p><strong>Repository:</strong> ${{ github.repository }}</p>
            <p><strong>Branch:</strong> ${{ github.ref_name }}</p>
            <p><strong>Commit:</strong> ${{ github.sha }}</p>
            <p><strong>Author:</strong> ${{ github.actor }}</p>
            <p><a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Run</a></p>

      - name: Send failure notification
        if: failure()
        uses: ./.github/actions/send-email
        with:
          smtp_server: ${{ secrets.SMTP_SERVER }}
          smtp_password: ${{ secrets.SMTP_PASSWORD }}
          sender: 'ci@yourcompany.com'
          receivers: 'team@yourcompany.com'
          subject: '❌ Build Failed - ${{ github.repository }}'
          body_file: 'error_report.html'
          max_retries: '5'
